name: Validation

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.11.2
      - name: Install action-validator
        run: cargo +stable binstall --no-confirm action-validator
      - name: Lint Actions
        run: |
          for file in .github/workflows/*.yml ; do
            echo "check $file"
            action-validator "$file"
          done
      - name: Validate codecov.yml
        run: |
          curl -f --data-binary @codecov.yml https://codecov.io/validate
  check-spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          inline: 'error'
          incremental_files_only: false
