name: Validation

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: "nixpkgs=channel:release-23.05"
      - name: Validate Cargo.toml
        run: nix develop .#validate -c taplo lint --schema https://json.schemastore.org/cargo.json Cargo.toml
      - name: Validate rust-toolchain.toml
        run: nix develop .#validate -c taplo lint --schema https://json.schemastore.org/rust-toolchain.json rust-toolchain.toml
      - name: Validate workflow files
        run: |
          nix develop .#validate -c action-validator .github/workflows/audit.yml
          nix develop .#validate -c action-validator .github/workflows/rust.yml
          nix develop .#validate -c action-validator .github/workflows/release.yml
          nix develop .#validate -c action-validator .github/workflows/validate.yml
      - name: Validate codecov.yml
        run: |
          curl -f --data-binary @codecov.yml https://codecov.io/validate
  check-spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v5
        with:
          inline: 'error'
          incremental_files_only: false
